#include <stdio.h>
#include <ctype.h>

// Global variable declaration
int charClass;
char lexeme [100];
char nextChar;
char *e = "Error: Next Lexeme is an Unknown Type\n";
int lexLen;
int token;
int nextToken;
FILE *in_fp, *fopen();

//Function declarations
void addChar();
void getChar();
void getNonBlank();
int lex();

//Character classes
#define LETTER 0
#define DIGIT 1
#define UNKNOWN 99

//Token codes
#define INT_LIT 10
#define IDENT 11
#define ASSIGN_OP 20
#define ADD_OP 21
#define SUB_OP 22
#define MULT_OP 23
#define DIV_OP 24
#define LEFT_PAREN 25
#define RIGHT_PAREN 26

//Main driver
main() {
//Open the input data file and process its contents
if ((in_fp = fopen("front.in", "r")) == NULL)
    printf("ERROR - cannot open main \n");
else {
    getChar();
    do {
        lex();
    } while (nextToken != EOF);
}
}

//lookup - a function to lookup operators and parentheses and return the token
int lookup (char ch) {
switch (ch) {
case '(':
       addChar();
       nextToken = LEFT_PAREN;
       accept("The token at the following location is a LEFT_PAREN\n", e);
       break;

case ')':
    addChar();
    nextToken = RIGHT_PAREN;
    accept("The token at the following location is a RIGHT_PAREN\n", e);
    break;

case '+':
    addChar();
    nextToken = ADD_OP;
    accept("The token at the following location is a ADD_OP\n", e);
    break;

case '-':
    addChar();
    nextToken = SUB_OP;
    accept("The token at the following location is a SUB_OP\n", e);
    break;

case '*':
    addChar();
    nextToken = MULT_OP;
    accept("The token at the following location is a MULT_OP\n", e);
    break;

case '/':
    addChar();
    nextToken = DIV_OP;
    accept("The token at the following location is a DIV_OP\n", e);
    break;

default:
    addChar();
    nextToken = EOF;
    accept(e, e);
    break;
}
return nextToken;
}

//addChar - a function to add nextChar to lexeme
void addChar() {
if (lexLen <= 98) {
    lexeme[lexLen++] = nextChar;
    lexeme[lexLen] = 0;
}
else
    printf("Error - lexeme is too long \n");
}

//getChar - a function to get the next character of input and determine its character class
void getChar() {
if ((nextChar = getc(in_fp)) != EOF) {
    if (isalpha(nextChar))
        charClass = LETTER;
        else if (isdigit(nextChar))
            charClass = DIGIT;
        else charClass = UNKNOWN;
    }
    else
        charClass = EOF;
}

//getNonBlank - a function to call getChar until it return a non-whitespace character
void getNonBlank() {
while (isspace(nextChar))
    getChar();
}


//lex - a simple lexical analyzer for arithmetic expressions
int lex() {
lexLen = 0;
getNonBlank();
switch (charClass) {
//Parse identifiers
case LETTER:
    addChar();
    getChar();
    while (charClass == LETTER || charClass == DIGIT) {
        addChar();
        getChar();
    }
        nextToken = IDENT;
        accept("The token at the following location is a LETTER\n", e);
        break;

//Parse integer literals
case DIGIT:
    addChar();
    getChar();
    while (charClass == DIGIT) {
        addChar();
        getChar();
    }
    nextToken = INT_LIT;
    accept("The token at the following location is a DIGIT\n", e);
    break;

//Parentheses and operators
case UNKNOWN:
    lookup(nextChar);
    getChar();
    break;

//EOF
case EOF:
    nextToken = EOF;
    lexeme[0] = 'E';
    lexeme[1] = 'O';
    lexeme[2] = 'F';
    lexeme[3] = 0;
    break;
    } //End of switch
    printf("Next token is: %d, Next lexeme is %s\n", nextToken, lexeme);
    return nextToken;
} //End of function lex

void expr() {
    printf("Enter <expr>\n");

    /* Parse the first term */
	term();

/* As long as the next token is +or -, get the next token and parse the next term */
while (nextToken == ADD_OP || nextToken == SUB_OP) {
    lex();
    term();

}
printf("Exit <expr>\n");
    } // End of function expr

/* factor
   Parses strings in the language generated by the rule:
   <factor> -> id | int_constant | ( <expr )
*/
void factor() {
    printf("Enter <factor>\n");

//Determine which RHS
if (nextToken == IDENT || nextToken == INT_LIT)

// Get the next token
lex();

/* If th RHS is ( <expr>), call lex to pass over the
left parenthesis, call expr, and check for the right
parenthesis */
else {
     if (nextToken == LEFT_PAREN) {
        lex();
        expr();
        if (nextToken == RIGHT_PAREN)
            lex();
        else
            printf("Error");//error();
     }// End of if (nextToken == ...

/* It was not an id, an integer literal, or a left
parenthesis */
else
  printf("Error");//error();
} //End of else
printf("Exit <factor>\n");
} //End of function factor

/* term
   Parses strings in the language generated by the rule:
   <term> -> <factor> {(* | /) <factor>}
*/
void term() {
    printf("Enter <term>\n");

// Parse the first factor
    factor();

/* As long as the next token is * or /, get the
   next token and parse the next factor */
   while (nextToken == MULT_OP || nextToken == DIV_OP) {
    lex();
    factor();
   }
   printf("Exit <term>\n");
    } //End of function term


//Accept method
void accept(char ntoken[], char *a) {
	if (lexLen <=  98) {
	printf(ntoken);
}
	else if (charClass == EOF || lexLen > 98) {
	printf(a);
}
	else {
	printf(a);
}
}
