apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: homarr
    meta.helm.sh/release-namespace: homarr
  creationTimestamp: "2025-10-31T18:29:16Z"
  labels:
    app.kubernetes.io/instance: homarr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: homarr
    app.kubernetes.io/version: 0.16.0
    helm.sh/chart: homarr-1.4.0
  name: homarr
  namespace: homarr
  resourceVersion: "20303"
  uid: 9ca4023d-089c-45b3-98d9-8c6713a6da51
spec:
  clusterIP: 10.43.168.67
  clusterIPs:
  - 10.43.168.67
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 7575
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: homarr
    app.kubernetes.io/name: homarr
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
