apiVersion: v1
kind: Pod
metadata:
  labels:
  name: nginx-storage
spec:
  containers:
  - image: nginx
    name: nginx
  volumes:
    - name: scratch-volume
      emptyDir:
        sizeLimit: 500Mi

  containers:
    - image:nginx
      name: nginx
      volumeMounts:
        - mountPath: /scratch
          name: scratch-volume
